### ISSUE TITLE
etcfs high cpu spikes

### ISSUE THREAD

**Issue by brudolp** [bedrocklinux/bedrocklinux-userland#116]
hi, some [time](https://www.reddit.com/r/bedrocklinux/comments/bedr2x/clearlinux_patches_for_archantergos/) ago I tried installing a clear linux strata (on top of antergos) and noticed that sometimes the cpu usage of etcfs was spiking up to 25% with an average usage of 7%. This also happened on a clean hijacked antergos without additional strata (similar values). Currently I am using kde neon (+ strata arch), etcfs is using 2-3% after boot, but something like this still occasionally happens: https://i.imgur.com/83vqvXs.png 
Hardware: celeron N3350 and emmc
is this expected behavior, and if not how can I help to debug this?

**Comment by paradigm** [comment]
This is expected behavior.

On Linux, when a userland program does something with the filesystem, it does not do it directly.  Instead, it tells the Linux kernel what it wants (i.e., makes a system call) and the Linux kernel handles it.  This is how things like permissions work, as it gives the Linux kernel the opportunity to check if the requesting program has adequate permissions before fulfilling the request.

Given this, there are two ways to measure CPU usage of userland programs.  You can measure just the CPU usage of the userland program itself, or you can do the CPU usage of the userland program *and* the CPU usage the kernel consumed on behalf of the userland program.

This is also how things work on Bedrock with *most* files and directories.  However, `/etc` (and `/bedrock/cross`) do something a bit different, called FUSE.  When a userland program makes a request to the kernel for something in `/etc`, the kernel forwards the request to Bedrock's `etcfs` process which figures out what to do, tells the kernel the results, and the kernel forwards it back to the original userland program.

This makes CPU usage tracking a bit more complicated.  Even if `etcfs` had no performance overhead itself, in practice it would get reported for CPU usage that it's actually doing for other userland programs.  If you run `while true; do find /etc >/dev/null 2>&1; done`, CPU reporting tools will cite `etcfs` as using a bunch of CPU that's actually arguably that script's CPU usage.  Pretending for a moment that `etcfs` had no CPU overhead itself, this means if that if you had 37 programs using `/etc` that each consume 1% CPU to do so on a traditional distro, it might end up looking on Bedrock like `etcfs` is using 37% CPU and they aren't any, depending on how you measure it.

It'd be nice to be able to claim that's entirely the issue, but sadly in practice `etcfs` also has a fair bit of CPU overhead.  The typical pattern of going userland -> kernel -> userland is a lot faster than userland -> kernel -> etcfs -> kernel -> etcfs -> kernel -> userland, which is roughly what's actually happening with `etcfs`.  In practice I've found that this overhead, while not ideal, is also not really a problem, as in practice people do not usually run intensive software out of `/etc`.  I have not done any real scientific benchmarking of `etcfs`, I've seen other FUSE benchmarks citing about 17% overhead.  My guess is that number is an ideal and `etcfs` is a bit more in practice, but not significantly so.

Happily there are a number of efforts to get `etcfs`'s general technique to be much faster - ridding us of that 17% - in the future such as [Direct-FUSE](http://www.pdsw.org/pdsw-discs17/wips/zhu-wip-pdsw-discs17.pdf) and [ExtFUSE](https://linuxplumbersconf.org/event/2/contributions/249/attachments/71/82/ExtFUSELPC2018.pdf).  However, it will likely be some time before they mature and filter to somewhere accessible for Bedrock's needs.

I believe what's happening in your situation is a mix of both of these two discussed things.  On the one hand `etcfs` is getting reported for stuff your system would be doing anyways and everything is fine, and on the other `etcfs`'s overhead is making things a bit more expensive than they would normally be.

-----

All that having been said, I don't want to dismiss this out-of-hand as a non-issue.  Maybe it's a non-issue on the machines I've tested on with different specifications than yours, but on yours it is different.  Have you noticed actual software running more slowly on Bedrock than a traditional distro?  If not and you're simply checking in about that reported CPU usage, we could probably safely disregard it as `etcfs` taking the heat for other programs you'd normally have.  However, if you have found that it's actually a problem, we can definitely take the time to rule out the possibility that `etcfs` is actually consuming a problematic amount of CPU.

If you really want to dig into it, consider trying to find what is calling `etcfs`  Maybe some program is reading something in `/etc` excessively, and you could tune that done.  Sadly `etcfs` does not currently easily expose debug info, but I can walk you through getting to it if need be, which could help report what is talking to it,

-----

Thinking it over, one not unlikely possibility is that `/etc/localtime` is being read a lot.  I know some software out there may check the time - and thus timezone - excessively.  If so, I think I have a trick we can try to bypass `etcfs` for specifically that file.  As a test, try making a script with this contents and running it as root:

```
#!/bedrock/libexec/busybox sh
tz_crosspath="$(realpath /etc/localtime)"
tz_stratum="$(/bedrock/libexec/getfattr --only-values --absolute-names -n 'user.bedrock.stratum' "${tz_crosspath}")"
tz_localpath="$(/bedrock/libexec/getfattr --only-values --absolute-names -n 'user.bedrock.localpath' "${tz_crosspath}")"
tz_fullpath="/bedrock/strata/${tz_stratum}${tz_localpath}"
for s in $(brl list); do
	strat "${s}" /bedrock/libexec/busybox mount --bind "${tz_fullpath}" "/etc/localtime"
done
```

This will use _another_ technique - one faster than FUSE - for just the `/etc/localtime` file.  On my system:

```
$ # before running above script
$ time sh -c 'for x in $(seq 1 7000); do cat /etc/localtime >/dev/null; done'
sh -c 'for x in $(seq 1 7000); do cat /etc/localtime >/dev/null; done'  0.08s user 0.35s system 4% cpu 10.030 total
$ # run script
$ sudo sh ./test.sh
$ # after
$ time sh -c 'for x in $(seq 1 7000); do cat /etc/localtime >/dev/null; done'
sh -c 'for x in $(seq 1 7000); do cat /etc/localtime >/dev/null; done'  0.07s user 0.35s system 4% cpu 9.430 total
```

A small (~6%) but consistent difference.  Maybe for you it'll be more pronounced?  There may be caching that obscures the difference, but I think that caching would also be in effect for real-world use cases, so maybe that's a good thing.

To revert this, you can run:

```
#!/bedrock/libexec/busybox sh
for s in $(brl list); do
	strat "${s}" /bedrock/libexec/busybox umount "/etc/localtime"
done
```

Or just reboot, as it won't persist across reboots.
