### ISSUE TITLE
i686 support

### ISSUE THREAD

**Issue by vit1-irk** [bedrocklinux/bedrocklinux-userland#125]
Currently most common distributions are still supporting this architecture (including Ubuntu, Debian and AUR), so please add this to your scripts

**Comment by paradigm** [comment]
I'm hesitant to add partial support for a given architecture, as it's going to confuse end users and, honestly, myself.  I'd rather indicate either Bedrock does support a given instruction set, or it does not, without having to qualify.

One of Bedrock's features is the ability to leverage `binfmt_misc` and `qemu-user-static` to have non-native CPU architecture strata.  To leverage this for a given CPU architecture, we require specific magic, mask, and offset values to identify a given binary as targeting that architecture.  I have i386 and i486 values, but I have not been able to find i586 or the i686 you've requested.  It's possible this value is not readily available because i386 or i486 should suffice, but my limited testing there did not pan out.  I could probably research how one would go about determining these values and derive them myself, but that's a lot of work and I am unlikely to get to it any time soon.

A closely related concern is that most qemu-user-static distribution packages, [such as Debian's](https://packages.debian.org/sid/arm64/qemu-user-static/filelist), do not explicitly provide a `qemu-i686-static`.  This could be because `qemu-i386-static` covers it, which would explain the missing `qemu-i486-static` despite the i486 magic/mask/offset being readily available.

If someone else collects the `binfmt_misc` magic, mask, and offset values for i686 (and i585 if it's not much extra work), and if `qemu-i386-static` will run such binaries such that this Bedrock subsystem will work for i686, I'll be delighted to begin distributing i686 binary installers and updates.  Until then, I'm likely to defer this in favor of more pressing or more quickly resolved issues for quite some time.  If I exhaust more pressing tasks, return to this task, and find myself unable to get i686 to work with `binfmt_misc` and `qemu-user-static`, I might add limited support and qualify accordingly, but I'd rather exhaust alternatives before doing so

**Comment by vit1-irk** [comment]
Can you at least add i386 if it is easier to recognize?

**Comment by paradigm** [comment]
I did in pre-release testing for the aforementioned non-native CPU architecture feature and received multiple reports about i686 not working.  I suspect many people blur the difference between x86 flavors, as for the vast majority of situations it does not make a difference for them.  I'd rather support all of x86 or none of it to avoid such confusion.  I'd rather not have to field regular queries about why distros such as Void Linux are not supported despite offering x86.

If, after exhausting more pressing tasks, I return to working on i586 and i686 non-native arch support and find I have to give up on it, I'll consider limited i386 and i686 support with corresponding warnings and documentation about what does and does not work.  It will likely be quite some time before I get to diving deeply into i686, and even more time before either figuring it out or giving up on the possibility.

If you want it for your personal use, consider compiling Bedrock yourself.  While I haven't tested it for aforementioned reasons, I would be surprised if it does not work.  The primary catch will be that `brl fetch` will not list any supported distros for your CPU architecture; you'll have to either manually adjust the back-ends for i386/i686 or [add strata manually](https://bedrocklinux.org/0.7/workflows.html#manually-adding-strata).

**Comment by paradigm** [comment]
I was able to get past the previous blockers here.  The binfmt registration information was a red herring.  The issue I was running into previously was a bug specific to the given qemu-i386-static build.  Newer qemu-i386-static builds work fine for our situation.

0.7.8 now supports i386, i486, i586, and i686 binary installers and updates.

I am closing this issue assuming these work fine.  If I missed something and they're inadequate, do feel free to reopen the issue.  If your interest here remains and you have the chance to try it out and they do work, do feel free to comment on the closed issue and let me know.
