### ISSUE TITLE
Unable to fetch ubuntu

### ISSUE THREAD

**Issue by fosslinux** [bedrocklinux/bedrocklinux-userland#147]
`brl fetch ubuntu` fails on the 'Running bootstrap software' (I think it is debootstrap) with the following error:

```
➜ sudo brl fetch ubuntu -r bionic -m https://ftp.swin.edu.au/ubuntu/ --help
[ 1/18 (  5%)] Determining name
* Using ubuntu
[ 2/18 ( 11%)] Determining CPU architecture
* Using x86_64
[ 3/18 ( 16%)] Determining release
* Using bionic
[ 4/18 ( 22%)] Determining mirror
* Using https://ftp.swin.edu.au/ubuntu/
[ 5/18 ( 27%)] Making bootstrap directory structure
[ 6/18 ( 33%)] Downloading package information database
Connecting to ftp.swin.edu.au (136.186.1.76:443)
saving to '/bedrock/strata/ubuntu/brl-bootstrap/Packages.gz'
Packages.gz          100% |********************************************************************************************************************************************************************| 1312k  0:00:00 ETA
'/bedrock/strata/ubuntu/brl-bootstrap/Packages.gz' saved
[ 7/18 ( 38%)] Converting distro package information database to brl format
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 8/18 ( 44%)] Calculating required bootstrap packages
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 9/18 ( 50%)] Downloading bootstrap packages
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[10/18 ( 55%)] Extracting bootstrap packages
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[11/18 ( 61%)] Running bootstrap software
I: Retrieving InRelease
I: Retrieving Release
E: Failed getting release file https://ftp.swin.edu.au/ubuntu/dists/bionic/Release
ERROR: Unexpected error occurred.
```

This release file very obviously exists, as can be seen using `wget` or a web browser.

**Comment by fosslinux** [comment]
Further testing indicates that this is not an issue with the one mirror, but with a variety of mirrors. It's not always the same error either. I cannot reproduce this with debian, nor any other distro.

---

```
➜ sudo brl fetch ubuntu -r bionic -m https://mirror.aarnet.edu.au/pub/ubuntu/
[ 1/18 (  5%)] Determining name
* Using ubuntu
[ 2/18 ( 11%)] Determining CPU architecture
* Using x86_64
[ 3/18 ( 16%)] Determining release
* Using bionic
[ 4/18 ( 22%)] Determining mirror
* Using https://mirror.aarnet.edu.au/pub/ubuntu/
[ 5/18 ( 27%)] Making bootstrap directory structure
[ 6/18 ( 33%)] Downloading package information database
Connecting to mirror.aarnet.edu.au (202.158.214.106:443)
wget: server returned error: HTTP/1.1 404 Not Found
ERROR: Unexpected error occurred.
```

```
➜ sudo brl fetch ubuntu -r bionic -m https://archive.ubuntu.com
[ 1/18 (  5%)] Determining name
* Using ubuntu
[ 2/18 ( 11%)] Determining CPU architecture
* Using x86_64
[ 3/18 ( 16%)] Determining release
* Using bionic
[ 4/18 ( 22%)] Determining mirror
* Using https://archive.ubuntu.com
[ 5/18 ( 27%)] Making bootstrap directory structure
[ 6/18 ( 33%)] Downloading package information database
Connecting to archive.ubuntu.com (91.189.88.162:443)
wget: error getting response: Connection reset by peer
ERROR: Unexpected error occurred.
```

```
➜ sudo brl fetch ubuntu -r bionic -m https://nl.archive.ubuntu.com
[ 1/18 (  5%)] Determining name
* Using ubuntu
[ 2/18 ( 11%)] Determining CPU architecture
* Using x86_64
[ 3/18 ( 16%)] Determining release
* Using bionic
[ 4/18 ( 22%)] Determining mirror
* Using https://nl.archive.ubuntu.com
[ 5/18 ( 27%)] Making bootstrap directory structure
[ 6/18 ( 33%)] Downloading package information database
Connecting to nl.archive.ubuntu.com (213.136.12.213:443)
wget: server returned error: HTTP/1.1 404 Not Found
ERROR: Unexpected error occurred.
```

---

There is a chance this is something very very weird with my connection; I will try tomorrow with an alternative connection.

Very strange any way.

My thoughts:

1. Networking error for the ubuntu script. I don't see anything triggering this, however.
2. More general brl-fetch error that just hasn't reared it's head anywhere else in the script or in other distros.
3. More general bedrock networking error not appearing anywhere else.

I feel like the first is the most likely.

**Comment by paradigm** [comment]
None of the mirrors you've provided appear to be valid Ubuntu package mirrors.  They don't work in, for example, `/etc/apt/sources.list` or when provided to `debootstrap`.  Maybe you misinterpreted whatever source you used to find them?

These ones:

- https://mirror.aarnet.edu.au/pub/ubuntu/
- https://archive.ubuntu.com
- https://nl.archive.ubuntu.com

are missing required suffixes:

- https://mirror.aarnet.edu.au/pub/ubuntu/archive/
- https://archive.ubuntu.com/ubuntu/
- https://nl.archive.ubuntu.com/ubuntu/

which is why their `brl fetch` runs errored out where they did.  I can look into making `brl fetch` provide more information at that step to make it easier to debug this, such as having it show the package information database URL it is attempting to use.

I cannot access https://archive.ubuntu.com/ubuntu/ at all.  This is because it does not use `https://`, but rather `http://`.  Note:

- None of the archive mirrors use https: https://launchpad.net/ubuntu/+archivemirrors
- None of the country code mirror requirements explicitly call out http and do not mention https: https://wiki.ubuntu.com/Mirrors
- There's been a whole bunch of arguing over the pros and cons of https for package mirrors leading to websites like: https://whydoesaptnotusehttps.com/

Using:

- http://ftp.swin.edu.au/ubuntu/
- http://mirror.aarnet.edu.au/pub/ubuntu/archive/
- http://archive.ubuntu.com/ubuntu/
- http://nl.archive.ubuntu.com/ubuntu/

all worked for me.

**Comment by fosslinux** [comment]
Oh, well, I'm stupid. I almost never use Ubuntu, so wasn't aware of that. The Ubuntu wiki didn't have the /archive on the end; this lead me to believe that there was no /archive. I was not aware that apt did not use https either. Thank you for the clarification and sorry for opening a issue about nothing bedrock-linux related :D

**Comment by paradigm** [comment]
No worries, happy to help
