### ISSUE TITLE
New bleeding kernel 5.17 does not cope well with Nvidia 390xx drivers

### ISSUE THREAD

**Issue by kskeigrshi** [bedrocklinux/bedrocklinux-userland#247]
So basically my friend has a test bench, and this computer has a GT 660, and it needs Nvidia 390xx drivers.
The latest 5.17 bleeding edge mainstream kernel seems to have a bed time with the drivers.
This is very weird, since my Alder Lake main desktop seems to work perfectly well with its RTX 3070 Ti.
As a note, kernel 5.16 seemed to work perfectly well, and it simply blinks constantly when booting.
This might not be an issue with Bedrock Linux itself since it seems to happen at systemd-level, but I'll open this issue because there's a possibility it actually could be.

https://user-images.githubusercontent.com/90227297/149881333-5520ade7-9a19-4467-8801-d9b1b59a2b63.mp4

---

Specs:
Ryzen 5 2600
GT 660
16GB RAM
GIgabyte B450M Motheboard

**Comment by paradigm** [comment]
[nVidia famously does not play very nicely with the Linux kernel community.](https://www.youtube.com/watch?v=_36yNWw_07g)  Unlike Intel and AMD, they do not provide the Linux kernel the information Linux needs to maintain compatibility across versions.  Consequently, Linux kernel updates commonly break the black-box proprietary nVidia driver compatibility.  The normal solution is to wait for nVidia to push out an update.  Being on a bleeding edge kernel exacerbates things, as the nVidia engineers may not have had time yet to rework things to be compatible with the given Linux release.  What you're seeing here could be completely normal and independent of distro.

The reason you're seeing this after the hand-off to systemd is likely because Bedrock's menu runs in a very portable limited graphics mode while systemd may be configured to kick off some graphical system (e.g. a graphical login menu).  It's not until systemd runs that something actually tries to really use the graphics card/drivers.  Bedrock doesn't actually do anything here that's relevant; your association in the video is a coincidence.

_Another_ issue specific to nVidia proprietary drivers is that the kernel module version and userland component version need to be paired.  There's limited forwards/backwards compatibility.  With Bedrock, each stratum has its own instance of the userland components.  Thus, [Bedrock users have to jump through some hoops to make sure all graphics-related strata have the same nVidia proprietary driver version](https://bedrocklinux.org/0.7/feature-compatibility.html#nvidia-drivers).  As far as I know this is the only way Bedrock is a factor for nVidia drivers.  Assuming you're properly maintaining this invariant, Bedrock shouldn't be a factor here.

Given that this is kind of thing is very common without Bedrock and that your reasoning pointing to it possibly being related to Bedrock is a coincidence as Bedrock doesn't _do_ anything relevant at that step, I'm closing this.  If you can show it working with [a Bedrock compatible distro](https://bedrocklinux.org/0.7/distro-compatibility.html) pre-hijack then immediately breaking after hijacking, feel free to provide the corresponding information and re-open it.
