### ISSUE TITLE
voidlinux /etc/sv and /var/service do not exist

### ISSUE THREAD

**Issue by AT-Geist** [bedrocklinux/bedrocklinux-userland#289]
I ran into a weird issue when I wanted to add the fcron service to my init-providing voidlinux stratum. The /etc/sv and /var/service directories do not exist. Yet /bedrock/strata/void-glibc/etc/sv does (I have both a void-glibc stratum and a musl stratum).

I'm not sure when this started since I didn't notice until now, but I am currently writing from the bedrock install and the services I had running (NetworkManager, sddm, etc...) are still working

**Comment by AT-Geist** [comment]
In a worst-case scenario, I'll reinstall (My /home is on a separate drive, so I won't lose too much). However, I'd like to figure out what happened so It can be avoided in the future

**Comment by aeknt** [comment]
does `strat void-glibc ls /etc/sv` show the services?
If yes, one possibility why they seem to exist is that your shell is provided another stratum, try running `brl which $$`
or perhaps, since you are adding the service, check which stratum provides sudo, doas or similar program from (the su should be provided by stratum from which is the current shell i guess)
If the shell or sudo are provided by different stratum than the void stratum you are trying to add service into, use `# strat void-glibc command`

**Comment by AT-Geist** [comment]
Ah, I'm using fish-git from the aur so my Artix stratum is providing sudo

**Comment by aeknt** [comment]
You may have to pin it if you want it to be mainly provided by the void
https://bedrocklinux.org/0.7/workflows.html#pinning

**Comment by AT-Geist** [comment]
It looks like it worked! 
I can see /etc/sh and /var/service again

Thank you for helping me out!
