### ISSUE TITLE
[Prob feature request] Plymouth compatibility on auto-select

### ISSUE THREAD

**Issue by Hexality** [bedrocklinux/bedrocklinux-userland#296]
Basically the title.

Is there a way to re-enable plymouth? I know that bedrock tries to kill it in order for it to not obscure the init selection menu, but that makes no sense at all if the timeout is set to 0.

**Comment by paradigm** [comment]
The current behavior has value even if the timeout is zero.  Consider what happens if the user switches to an init that isn't configured to stop Plymouth, in which case they'd never see the login prompt.  That said, not everyone leverages Bedrock's ability to swap out inits, and it does make sense to make your requested behavior configurable.

Until it's configurable, you can hack around the current behavior by either:

- Commenting out or removing [the `/bedrock/libexec/plymouth-quit` line](https://github.com/bedrocklinux/bedrocklinux-userland/blob/d1783c20cb0034c970350f2d38fa2f5a1482402d/src/init/init#L30-L32) from `/bedrock/strata/bedrock/sbin/init`
- Removing or renaming `/bedrock/libexec/plymouth-quit` and replacing it with an empty file that has execute permissions.

Note this'll get blown away in a following `brl update`.

**Comment by Hexality** [comment]
I only do `brl update` if explicitly necessary to avoid problems, so I'm good anyways.
Thank you for providing the path, I was actually trying to find what was killing Plymouth.

**Comment by Hexality** [comment]
is there a way to rename the original strata name? (ex.: from fedora (hijacked system) to something else)

**Comment by aeknt** [comment]
`brl rename`
but you need to disable the stratum first `brl disable`, so you need to boot via another stratum
for example see `brl <something> --help`
