### ISSUE TITLE
[RFC] Leverage the namespace feature of Linux 

### ISSUE THREAD

**Issue by yshui** [bedrocklinux/bedrocklinux-userland#66]
# Why?

Because things happen in other strata is way too visible in the main stratum. Resulting in:
- Huge number of mount points listed in /proc/mounts
- Init confused by disappearing slave mountpoints
- Not able to run the native init system of each stratum
# How?

My plan is still incomplete, but it's roughly like this:

Each stratum will resides in its own filesystem and pid namespace, which is setup by bedrock before the first init runs. After namespace is created, bedrock will move mount the stratum root to /, and execute /sbin/init.

Shared mounts will propagate through filesystem namespaces, so that won't be a problem.
# Pros
- You won't see a long lists of mount points anymore
- You can use each stratum's native init system
# Cons

Feature-wise, none. You should still be able to do whatever you can do now.

Implementation-wise, executing programs from another stratum will become a little more complex. But this is handled by brc, so it's transparent to the user.
# Difficulties

I still need to figure out how filesystem namespace will interact with shared mounts. From the experiments I've done, it's clearly possible to maintain the current behavior of bedrock. But the way mountpoints is managed might need to change

**Comment by paradigm** [comment]
Regarding mount namespaces:

- I find both the long mount list and warnings from init systems about slave
  mountpoints disappearing ugly.  However, they're both very minor/ignorable
  issues - fixing them is not worth much of a sacrifice elsewhere.

- Hiding mounts from init means they won't automatically be unmounted on
  shutdown.  That could be a serious issue.

- We'd lose the ability to interact with non-global mounts through
  `/bedrock/strata/`.  This isn't a common/regular thing in any workflow I've
  seen, *and* it's only really feasible from the init stratum, but it's still a
  minor loss worth keeping in mind.  It's possible, for example, for a stratum
  to have a FUSE filesystem but not `fusermount` such that someone has to `brc`
  another stratum's `fusermount`.

Regarding PIDs/init:

- The fact that only one stratum's init-related things "just work" the largest
  open problem with Bedrock Linux that doesn't have any plan on the roadmap to
  fix before 1.0 stable.  If we can cleanly fix it I'd be all for it.
  However...

- Utilizing PID namespaces doesn't immediately allow for clean use of multiple
  init systems; instance on PID1 isn't the only blocker.  The init systems
  would end up fighting over things like `/dev`, for example.  Multiple
  systemds interacting with one dbus seems like a nightmare, and having
  multiple segregated dbus instances is actively detracting from what Bedrock
  Linux is supposed to do.

- PID namespaces completely break common workflow assumptions.  Users should
  not have to worry about scenarios in which a `ps` provided PID differs from
  an `htop` provided PID.

UID/GID namespaces are also *potentially* useful here if we can avoid their
drawbacks.  Right now I recommend against dual-booting a Bedrock Linux install
with one of its strata due to concerns that the stratum will do things like add
users or groups and the UID/GIDs will get de-synced.  UID/GID namespaces could
fix that.  However, not unlike what happens with PID namespaces, that'd result
in scenarios where two different programs will get different UID owners from
the same exact file, which would be bad.

**Comment by yshui** [comment]
## Mount namespaces

> Hiding mounts from init means they won't automatically be unmounted on shutdown. That could be a serious issue.

Bedrock will have a chance to take over the system when init exits, if we uses the PID namespace (For this purpose we just need one PID namespaces for all strata). Then we can do the unmounts there.

> We'd lose the ability to interact with non-global mounts through `/bedrock/strata/`.

Like I said, shared mounts can propagate through mount namespaces (we just need figure out exactly how they are propagated), so I don't think this will be a problem.

## PID namespaces

> The init systems would end up fighting over things like /dev, for example

This should be solved by using mount namespaces?

> Multiple systemds interacting with one dbus seems like a nightmare

I agree this is a potential problem. But the current implementation is not problem free either. e.g. dbus services installed in other strata (i.e. a stratum that doesn't run the system dbus daemon) can't be activated through dbus.

> PID namespaces completely break common workflow assumptions. Users should not have to worry about scenarios in which a ps provided PID differs from an htop provided PID.

Hmm, maybe we can put them in /bedrock/brpath/pin?

**Comment by yshui** [comment]
@paradigm 
> The fact that only one stratum's init-related things "just work" the largest open problem with Bedrock Linux that doesn't have any plan on the roadmap to fix before 1.0 stable.

This RFC isn't for 1.0 stable either :)

**Comment by paradigm** [comment]
> > Hiding mounts from init means they won't automatically be unmounted on shutdown. That could be a serious issue.

> Bedrock will have a chance to take over the system when init exits, if we uses the PID namespace (For this purpose we just need one PID namespaces for all strata). Then we can do the unmounts there.

Hmm.  I'm not entirely sure I see how that'd work.  Once an init from a stratum calls `reboot(2)` the system powers off, even if the Bedrock Linux PID1 hasn't unmounted everything yet.

> > We'd lose the ability to interact with non-global mounts through /bedrock/strata/.

> Like I said, shared mounts can propagate through mount namespaces (we just need figure out exactly how they are propagated), so I don't think this will be a problem.

Maybe you're seeing something I don't.  I'm at a complete loss for a clean way to do this.

> > The init systems would end up fighting over things like /dev, for example

> This should be solved by using mount namespaces?

Further segregating things?

- Would every stratum then need to manage its own `/dev`?  Or would we have additional configuration to indicate where strata which don't manage their own `dev` should go to get one?  If the former, this would be a pretty major drop in functionality, and if the latter it'd make configuration even more complicated.
- What happens when the various `/dev`s get out of sync?
    - I could easily see someone's gamepad work with software from one stratum but not another in a way that would seriously confuse end users and be a pain to debug.
    - The thought that `/dev/sda` and `/dev/sdb` could be swapped in two different `/dev`s is horrifying.
- Is there any software out there that depends on `/dev` being the same for various processes?  If I remember correctly `gpg`/`pinentry` can open a curses UI "over" a given application's UI (e.g. `mutt`) to prompt for a password.  Will that work if `gpg`'s `/dev/pts/` is different from the calling process's?

> > Multiple systemds interacting with one dbus seems like a nightmare

> I agree this is a potential problem. But the current implementation is not problem free either. e.g. dbus services installed in other strata (i.e. a stratum that doesn't run the system dbus daemon) can't be activated through dbus.

If I'm not confusing this with something else, I was working with someone in the IRC room to fix exactly this issue.  We had some promising results in proof-of-concept tests.  This may not be a fundamental issue with having a single dbus instance.

Even if it *was*, I don't see how the RFC helps here.  The fact that *some* desired features are missing/broken doesn't mean we should go out and break others.

> > PID namespaces completely break common workflow assumptions. Users should not have to worry about scenarios in which a ps provided PID differs from an htop provided PID.

> Hmm, maybe we can put them in /bedrock/brpath/pin?

I don't see how that'd help.

Maybe an example workflow problem would help illustrate the issue: say a sysv-style init from stratum `A` creates a pid file.  The user wants to learn more about the process to which it refers, so he cracks open `htop`, where `htop` is only available from stratum `B`.  We intercept the call to `htop`.  Now what?

> This RFC isn't for 1.0 stable either :)

Oh good, good.

-----

I'm not overly hopeful we can resolve the places where the namespace usage breaks expected workflow/features (and, fundamentally, Bedrock Linux's goal).  I'm certainly happy to continue discussing it in that direction, though - I could easily be missing something.

However, there's an alternative that may be worth mentioning: we retain the current architecture/workflow for *some* strata, but optionally allow for namespace-confined container-style strata as a separately configured option.  This would allow *most* strata to interact just like they currently do, but *also* allow some strata to have their own PID1/init.  Those container-ized strata could provide things like libvirtd as needed for kvm/qemu.

Honestly, I don't like this idea:

- It effectively recreates the existing functionality provided by LXC, Docker, systemd-nspawn, etc.  No need for us to reinvent the wheel here.  If an upstream distro/project can provide a given piece of functionality, Bedrock Linux should just get it from there.
- It'd be way to easy for users to get confused and try to make the container-style strata interact with the rest of the system in ways they can't reliably do so.

However, I thought perhaps the idea may be useful food for thought.
