### ISSUE TITLE
create a milestone

### ISSUE THREAD

**Issue by Mouvedia** [bedrocklinux/bedrocklinux-userland#71]
https://github.com/bedrocklinux/bedrocklinux-userland/milestones/new

Create milestones so that we can review the Github issues you wanna tackle in the next releases.

**Comment by paradigm** [comment]
Milestones don't really fit the workflow Bedrock Linux has been using thus far.  We can certainly change the workflow if there's good reason, but it's been working for us so far.  If you think I'm missing something here, do feel free to point it out.

The way things work now:

- We've got a pool of issues.  Developers who have the skill/background/time/interest go after the ones they want.  When we have enough to be meaningful - usually but not necessarily including at least one major under-the-hood change - we test it for a bit then kick it out the door as another release.

Some background which may help illustrate why milestones may not work well:

- It's hard to plan more than one release ahead:
	- There is no over-arching plan for how to get Bedrock Linux to do everything we'd like it to do.  In fact, it's not even clear it's possible for Bedrock Linux to do everything we'd like it to do.  Broadly, the plan is to do as much as we can then cut a 1.0 stable release after we've given up on all the remaining under-the-hood things (and spent a lot of time polishing/testing/etc).  I can't plan a hard roadmap to 1.0 given that I don't know what's even possible on the road to get there.
	- When we do figure out how to do something, it often requires major under-the-hood changes to how Bedrock Linux works.  This makes it difficult to plan for features more than one release ahead, as things may easily change too much for any such plans to work out.
	- It's not clear what the most desirable features of release N+1 are until we've used release N for some months and gotten a feel for the biggest remaining issues.  It's not clear how helpful a given feature will turn out to be until we've actually used it.  This makes planning for N+2 largely infeasible.
- There have been a relatively small number of constant developers and a relatively large number of transient developers who may or may not stick around.
	- Any issues which don't require much Bedrock Linux specific background, or don't require as much Linux/C/shell/etc knowledge, are purposefully left open for these transient developers.  It'd not only be wasteful for the constant developers to tackle these when they could be doing something less accessible, but it also makes it harder for newbies to contribute if there's no low-hanging fruit.  I don't want to put them on a milestone such that there's any pressure to get them done for a specific release.
	- A lot of the transient people come in wishing to make a specific improvement.  Provided I agree that's an improvement, that's fine with me - no reason to have them feel pressured to work on something for the upcoming milestone if they don't care about it.
	- A lot of the transient people work on some issue then disappear before having completed it.  If it were on some milestone there'd be pressure to pick up their work, which may not be desirable.  As it is, we can just throw it back into the pool for someone else to take whenever they want.

If you disagree with the workflow despite the description above do let me know, maybe I'm missing something.

If your goal here is to contribute and you don't know how to pursue that without milestones:

- If you want to want to work on something specific, let me know - usually done via the IRC room, but github issues or whatever else you're more comfortable with could work - so we can discuss it to make sure we're all on the same page about the details and that the issue is not already being pursued, then feel free to go after it.  Once it's done it'll likely be included in the following release.

- If you want to contribute but you don't know specifically what to work on, let me know - again, usually done via IRC but something else could be fine - and we'll find you something based on your background/skillset and interests.  Expertise with C, Shell, Makefiles, or less common distros (e.g. NixOS) are all very useful.

**Comment by Mouvedia** [comment]
That makes perfect sense. Thanks for the lengthy explanation.
