### ISSUE TITLE
Error building on ArchLinux

### ISSUE THREAD

**Issue by du5tball** [bedrocklinux/bedrocklinux-userland#76]
Hello there,

I'm trying to build bedrock on ArchLinux (a VM installed today, just for this purpose), but I'm getting an error during compilation: [paste](https://ptpb.pw/pt8V).

Update: Installing "musl" from the repositories and using that as the compiler fixes "/usr/bin/ld: /home/user/bedrock/build/lib/crt1.o: relocation R_X86_64_32S against symbol `_fini' can not be used when making a shared object; recompile with -fPIC"

Edit: I found the issue. Arch uses GCC 7. After reworking it to use gcc5, the compile finishes as expected.

**Comment by paradigm** [comment]
Good job figuring out the relationship to compiler version; that helped me narrow down the underlying issue a fair bit.  Over IRC you also found the issue is relate to musl, which further helped quite a bit.

I was able to reproduce the issue, and in the process of hunting it down found another issue as well.  I've delivered changes which resolve the issue for me.  I tested them against:

- gcc 4.9.2 (from Debian OldStable/Jessie)
- gcc 5.3.1 (from Ubuntu Xenial/LTS)
- gcc 6.3.0 (from Debian Stable/Stretch)
- gcc 7.1.1 (from Arch)

and they all look good to me.

Please try against the latest 1.0beta2 or master commits and let me know if it resolves the issue for you.

When you try again, make sure there's no prior state.  Either re-clone so everything's fresh, or if you `git pull` be sure to remove pre-existing state via `make clean_source_all clean`.  At which point `make` should work for you.

**Comment by du5tball** [comment]
That one fixed it.
