### ISSUE TITLE
Add sbin to $PATH

### ISSUE THREAD

**Issue by du5tball** [bedrocklinux/bedrocklinux-userland#78]
I'm not sure if this is a bug or something that is actually supposed to be this way, but I installed "rinse" in a xenial stratum. Both "which" and "brw" told me that rinse isn't available (in $PATH) as a normal user, but as root I can execute it.

Please add the *sbin*-paths to $PATH, if you're not supposed to run something as root the program will happily tell you anyways (this is also the reasoning behind the [s,]bin-merge in ArchLinux by the way).

Edit: I've been made aware of NPATH and SPATH, and I propose the merging of both, as the program will tell you anyways.

**Comment by paradigm** [comment]
Bedrock Linux is targeting a very wide audience, and realistically there won't be a set of defaults that make everyone happy.  Some people prefer the merged bin/sbin, while others like the fact that root-only commands don't get tab-completed when running in a non-root shell.  If there was a consensus I'd go along with it, but it appears there are plenty of distros which continue to retain the distinction between bin and sbin directories.

Whichever way we go, the sysadmin can edit `/bedrock/etc/rc.conf` or users can change their `$PATH` in their shell's rc file or local profile, so I don't view terribly much friction here if people prefer something other than the default.

My reasons for picking the current setup, keeping sbin out of non-root user `$PATH`s, is:

- It's easier to append to the `$PATH` than filter items out.  If someone wants it, I think this is less friction than the other way around.
- Users who are on distros which transitioned to merged bin-sbin are more likely to be aware of the two styles here and should figure out what's going on and adjust easier than people who have always only known the separate bin-sbin style.
- That's how it currently is, and changing it is more friction than leaving it.

I don't see any reasons to favor the other direction, so it is as it is.

I'm not terribly firm on this and could likely be swayed by a good argument or technical need.

It may also be worth noting that a lot of root-only utilities will show up in the bin-only `$PATH` if one of your stratum has merged bin and sbin.  For example, Arch's merged bin-sbin means my Bedrock Linux default non-root `$PATH` includes fsck, because Arch provides it in `/bin/`.  This will annoy the people who prefer having root-only not show up in tab completion lists when running as non-root.

**Comment by paradigm** [comment]
I did so with Poki.
