### ISSUE TITLE
Installation guide for new fedora systems

### ISSUE THREAD

**Issue by du5tball** [bedrocklinux/bedrocklinux-userland#79]
As rinse doesn't provide ways to install a current fedora (the latest default is 19, ubuntu has 22 as the latest), I found a new one:

I've installed centos 7 as a stratum from rinse, and made the fedora repo available to yum. The command line then is:

yum --disablerepo='*' --enablerepo='fedoraproject' --installroot=/bedrock/strata/fedora26 groupinstall 'Minimal Install'

There should probably be a better way to abstract this, but it works until there's a more general way available.

**Comment by paradigm** [comment]
I'm hoping [brg](https://bedrocklinux.org/1.0beta3/plans.html#brg) will remove the need to advertise strategies such as the one you've proposed.  However, since `brg` is not yet available and `rinse` apparently isn't an option any more, we'll need to change something.  I'll leave this open until either I update the website with some other instructions, such as what you've proposed, or `brg` is done and fielded.

**Comment by paradigm** [comment]
Poki now has `brl fetch` which supports acquiring Fedora without any external tools like `rinse`.
