### ISSUE TITLE
alpine's apk doesn't work without sudo

### ISSUE THREAD

**Issue by emacsomancer** [bedrocklinux/bedrocklinux-userland#81]
With Alpine Linux installed in a stratum, 

if I run `apk search vim`, I get `zsh: command not found: apk`

if I run `sudo apk search vim`, then `apk` runs normally and produces expected output.

Likewise, `brc alpine apk search vim`:
`brc: could not run
    apk
in stratum
    alpine
due to: unable to find file (ENOENT)`

Chrooting into the Alpine layer, `apk search` &c. runs as expected without `sudo`.

**Comment by paradigm** [comment]
Some distros have `sbin` items in the default non-root path, some don't.  Whichever way Bedrock Linux goes about it would confuse a subset of the audience.  Bedrock Linux currently defaults to keeping sbin items out of the non-root path.  It's trivial to re-add them.

Note the NPATH and SPATH items in /bedrock/etc/r.conf as documented [here](https://bedrocklinux.org/1.0beta2/configure.html#npath).  If you append the SPATH items to NPATH and clear out SPATH, like so:

    NPATH=/opt/bin:/usr/local/bin:/usr/bin:/bin:/opt/sbin:/usr/local/sbin:/usr/sbin:/sbin
    SPATH=

Then sbin items should show up in non-root user `$PATHS` by default on next login.

Alternatively, you can leave rc.conf and set this per-user by appending the relevant fields to the user's `$PATH` in their shell's rc or local profile.

On my system, `/bedrock/alpine/etc/apk/repositories` was not readable by non-root which kept me from being able to use `apk` to search as non-root.  I don't know if this is expected for alpine/apk, or if it is due to a bad umask or something when I set up alpine.  If you know alpine expects that file to be world readable, do make sure the permissions on it are as appropriate.  I might have to update [these instructions](https://bedrocklinux.org/1.0beta2/strata.html#alpine) to make sure the file is world-readable if that's the expected setup on alpine.

**Comment by emacsomancer** [comment]
In plain vanilla Alpine, `apk` works as non-root for things like searching (but not, of course, for installing), so `apk search blah` is expected to work.

**Comment by paradigm** [comment]
Hm, alright.  I'll look into adjusting the instructions I use to acquire alpine to make sure `/bedrock/strata/alpine/etc/apk/repositories` is world-readable.

Reviewing my work here, the specific example I gave above doesn't work.  The key directory you need in your `$PATH` is `/bedrock/brpath/sbin/`, which wasn't in my example.  I'll adjust things so it is explicitly mentioned in `rc.conf` going forward.  Either `/bedrock/brpath/sbin/` to `NPATH` in `/bedrock/etc/rc.conf` or to your `$PATH` by some other means such as your shell's rc or local profile.

Also, be sure to change permissions on `/bedrock/strata/alpine/etc/apk/repositories` if necessary.

Let me know whether or not this resolves the issue for you.

**Comment by emacsomancer** [comment]
I'll have to check on the permissions.

**Comment by Yardanico** [comment]
Works for me on latest Poki:
```
➜  ~ brl which apk
alpine
➜  ~ brl which sudo
void
➜  ~ apk search vim
charybdis-3.5.5-r4
vim-8.1.0115-r0
graphviz-2.40.1-r1
vim-doc-8.1.0115-r0
py-jinja2-vim-2.9.6-r0
vimdiff-8.1.0115-r0
asciidoc-vim-8.6.10-r0
nginx-vim-1.14.1-r0
msmtp-vim-1.6.6-r3
protobuf-vim-3.5.2-r0
gst-plugins-base-1.14.0-r1
mercurial-vim-4.6.1-r0
➜  ~ sudo apk search vim
charybdis-3.5.5-r4
vim-8.1.0115-r0
graphviz-2.40.1-r1
vim-doc-8.1.0115-r0
py-jinja2-vim-2.9.6-r0
vimdiff-8.1.0115-r0
asciidoc-vim-8.6.10-r0
nginx-vim-1.14.1-r0
msmtp-vim-1.6.6-r3
protobuf-vim-3.5.2-r0
gst-plugins-base-1.14.0-r1
mercurial-vim-4.6.1-r0
➜  ~ strat alpine apk search vim
charybdis-3.5.5-r4
vim-8.1.0115-r0
graphviz-2.40.1-r1
vim-doc-8.1.0115-r0
py-jinja2-vim-2.9.6-r0
vimdiff-8.1.0115-r0
asciidoc-vim-8.6.10-r0
nginx-vim-1.14.1-r0
msmtp-vim-1.6.6-r3
protobuf-vim-3.5.2-r0
gst-plugins-base-1.14.0-r1
mercurial-vim-4.6.1-r0
```

**Comment by paradigm** [comment]
Resolved in Poki
