### ISSUE TITLE
Problems with `git clone --recursive`

### ISSUE THREAD

**Issue by SolitudeSF** [bedrocklinux/bedrocklinux-userland#88]
After installing bedrock on void `git clone --recursive https://github.com/bedrocklinux/bedrocklinux-userland` (works with any repo) fails with 
```
/usr/libexec/git-core/git-submodule: 1: /bedrock/cross/sbin/gettext.sh: Syntax error: "(" unexpected
```

**Comment by paradigm** [comment]
I can't immediately reproduce your issue, but I have theories for what's going on and how to work around it for your case.  First, before providing you a workaround, let's get a bit more information that I could use to reproduce the issue.  What is the output of these two commands?

- `brl which /usr/libexec/git-core/git-submodule`
- `brl which /bedrock/cross/sbin/gettext.sh`

That should indicate which stratum provides both of those components.  If it's not obvious from the stratum names, let me know which distros they correspond to as well.  Ideally I'll be able to install them from the same distros and reproduce your issue.

I suspect the underlying problem here is that whatever stratum provides `git-submodule` does *not* also provide `gettext.sh`.  Bedrock figures if `gettext.sh` was a hard dependency with specific version requirements, the package manager would ensure it's also available, so it's probably not a version-sensitive dependency.  Thus it's free to get it from another stratum.  However, maybe that's not the case.

Assuming my suspicion is correct:

- You should be able to run `strat <distro-that-provides-git-submodule> git clone --recursive https://github.com/bedrocklinux/bedrocklinux-userland` and get an error message about `gettext.sh` missing because the package manager didn't install it despite it being a dependency.
- You should be able to work around it by just installing whatever package provides `gettext.sh` from the same stratum that provides `git-submodule`.  Bedrock will see they're both from the same stratum and ensure they match up.

If I'm able to reproduce it with the additional requested information, I'll see what I can do to fix it in general.  If nothing else, I'll document it in time for Poki's post-beta release next month.

**Comment by SolitudeSF** [comment]
```
 ▲ ~  brl which /usr/libexec/git-core/git-submodule                                                                    
void

 ▲ ~  brl which /bedrock/cross/sbin/gettext.sh                                                                         
arch
```

running `strat --restrict <distro-that-provides-git-submodule> git clone --recursive https://github.com/bedrocklinux/bedrocklinux-userland` with either void or arch gives no error.

and installing `gettext` from void fixes issue entirely. thats strange because i didnt have it installed before bedrock, and there were no errors, so i assume it wasnt needed.

**Comment by paradigm** [comment]
I was able to reproduce the issue and figure out what's going on.  I wasn't *quite* on the money with my guess earlier.

[`git` supports multiple internationalization options, and uses the first one it finds in the environment](https://github.com/git/git/blob/373803158198310ba6ce68bfa054191038d87352/git-sh-i18n.sh#L18-L40).  On your initial pre-hijack Void system, `git` didn't see `gettext.sh`, so it fell through to some other option and seemed to work fine.  Once you hijacked and fetched an Arch stratum, `git` now saw Arch's `gettext.sh`, so it tried it then found some compatibility issue and generated the issue.  Once you installed Void's `gettext`, it saw Void's `gettext` in the environment and used it and was happy.

Apparently `gettext.sh` is an *optional* `git` dependency that's picky about versions.  I have seen this when people build distro generic code bases, e.g. with `autoconf` scripts.  However, I've never seen that happen with a distro package manager provided executable before.  Bedrock does not currently have any way to automatically recognize that situation.  I'll have to think about how to automate detecting and handling that.  It might be tricky.  The only thought I have at the moment along these lines is to add a blacklist of things that are explicitly disabled across stratum boundaries and include `gettext.sh` in the list.

For the time being, I plan to document this kind of situation before Poki's post-beta release and propose two work arounds:

- Install whatever cross-stratum thing is coming up in the calling process' stratum.
- Alternatively, use `strat -r` to disable cross-stratum stuff.

I'd like as much as possible to "just work" with Bedrock, and it's frustrating to have these corner cases where the user has to manually intervene, but that's where the project is at this point in time.

**Comment by paradigm** [comment]
Documented it with Poki's release
